import json

example_cfg = {
    "p": 64,
    "K": 6,
    "beta": 1.0,
    "method": 0,
    "l_max": 10.0,
    "n_samples": 1000,
    "intercept": False,
    "optimizer": "adam",
    "lr": 0.001,
    "n_epochs": 500,
    "wd": 0.0,
    "n_test_data_pred": 5,
    "f1_thres": 0.55,
    "path_to_results": "./results",
    "name_exp": "logistic_vi_example",
    "verbose": True,
    "data_channels": 3,
    "data_size": 64,
    "N": 1024,
    "N_test_ratio": 0.2,
    "coloured_background": False,
    "coloured_figues": False,
    "no_overlap": False,
    "bias_classes": [0.5, 0.5, 0.0, 0.0, 0.0, 0.0],
    "simplicity": 3,
    "main_dir": "/shared/sets/datasets/vision/artificial_shapes",
    "wandb": False,
}

with open('example_config.json', 'w') as f:
    json.dump(example_cfg, f, indent=4)
    # {
    #     "p": 64,
    #     "K": 6,
    #     "beta": 0.0,
    #     "method": 0,
    #     "l_max": 10.0,
    #     "n_samples": 1000,
    #     "intercept": False,
    #     "optimizer": "adam",
    #     "lr": 0.001,
    #     "n_epochs": 500,
    #     "wd": 0.0,
    #     "n_test_data_pred": 5,
    #     "f1_thres": 0.55,
    #     "path_to_results": "./results",
    #     "name_exp": "logistic_vi_example",
    #     "verbose": True,
    #     "data_channels": 3,
    #     "data_size": 64,
    #     "N": 1024,
    #     "N_test_ratio": 0.2,
    #     "coloured_background": False,
    #     "coloured_figues": False,
    #     "no_overlap": False,
    #     "bias_classes": [0.5, 0.5, 0.0, 0.0, 0.0, 0.0],
    #     "simplicity": 3,
    #     "main_dir": "/shared/sets/datasets/vision/artificial_shapes",
    #     "wandb": False
    # }